account/urls.py
from django.urls import path, re_path
from . import views
from .uploads import upload_image

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name="register"),  # 注册
    path('person/', views.person_center, name="person"), # 个人中心
    path('edit_user/', views.edit_user, name="edit_user"), # 编辑用户信息
    path('person_article/', views.person_article, name="person_article"), # 查询当前登录用户已经发布的文章
    path('person_add_article/', views.person_add_article, name="person_add_article"),  # 添加文章

    re_path('^upload/(?P<dir_name>[^/]+)$', upload_image, name='upload'),   # 富文本编辑器上传图片功能
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'^(?P<slug>[\w]+)/$', views.category, name='category'),
    path('article/<int:article_id>/', views.article, name="article"),
    path('comment/<int:article_id>/<int:comment_id>/', views.article, name="comment"),
    path('dates/<int:year>/<int:month>/', views.blog_get_dates, name="dates"),   # 归档页
    path('tags/<int:tag_id>/', views.blog_get_tags, name="tags"),      # 文章标签列表页
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    """博客分类模型."""
    name = models.CharField('分类名称', max_length=50)    # 标题字段
    slug = models.SlugField(max_length=50)   # Slug是一个报纸术语。SlugField表示定义短标签，只包含字母，数字，下划线或连字符，通常用于URL。
    desc = models.TextField('分类描述')  # 内容字段，用于存储大段文本
    add_date = models.DateTimeField('发布日期', auto_now_add=True)  
    # DateTimeField时间字段，当设置 auto_now_add=True ,当你首次发布信息时自动保存你首次发布的时间。
    # 当设置 auto_now=True ,那么在每次修改信息时都将自动保存为当前日期时间
    pub_date = models.DateTimeField('修改日期', auto_now=True)


    class Meta:
        """Meta definition for Category."""

        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of Category."""
        return self.name


class Tags(models.Model):
    """文章标签"""
    tag = models.CharField('文章标签', max_length=20, help_text='文章标签')
    add_date = models.DateTimeField('发布日期', auto_now_add=True)
    pub_date = models.DateTimeField('修改日期', auto_now=True)

    class Meta :
        ordering = ['-tag']
        verbose_name = '标签管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Article(models.Model):
    """博客文章模型."""
    title = models.CharField('文章标题', max_length=68)
    # 多对一关联字段ForeignKey，将多篇文章关联到某一个指定分类
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    # 关联到某一个作者
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_related', verbose_name="作者")
    desc = models.TextField('文章描述', max_length=200, blank=True, default='')
    content = models.TextField('文章内容')
    tags = models.ManyToManyField(Tags, verbose_name="文章标签")
    add_date = models.DateTimeField('发布日期', auto_now_add=True)
    pub_date = models.DateTimeField('修改日期', auto_now=True)

    class Meta:
        """Meta definition for Article."""
        ordering = ['-add_date']
        verbose_name = '博客'
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of Article."""
        return self.title


class Comment(models.Model):
    """评论管理"""
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="所属文章")
    content = models.CharField('评论内容', max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者") 
    add_date = models.DateTimeField('评论日期', auto_now_add=True)
    pub_date = models.DateTimeField('修改日期', auto_now=True)
    
    class Meta:
        """Meta definition for Comment."""

        verbose_name = '评论管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of Comment."""
        return self.content

blog/forms.py
from django import forms
from .models import Comment
# class CommentForm(forms.Form):
#     """创建留言框"""
#     text = forms.CharField(label="评论内容", widget=forms.Textarea(attrs={
#         'class': 'textarea is-radiusless is-shadowless', 'rows':6}))

class CommentForm(forms.ModelForm):
    """创建留言框"""
    content = forms.CharField(label="评论内容", widget=forms.Textarea(attrs={
        'class': 'textarea is-radiusless is-shadowless', 'rows':6}))

    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, reverse
from django.utils import timezone
from django.core.cache import cache, caches  # 缓存框架
# Create your views here.
from .models import Category, Article, Tags, Comment       # 引入菜单模型类 
from .forms import CommentForm


def index(request):
    """首页函数，把首页想要显示的内容都在这里查询"""
    article_list = Article.objects.all()    # 查询到文章的所有数据，显示到首页
    context = {'article_list':article_list}  # 定义上下文
    return render(request, 'blog/index.html', context)


def category(request, slug):
    """获取当前分类，并查询到当前分类的所有文章"""
    category = get_object_or_404(Category, slug=slug)
    return render(request, 'blog/category_list.html', locals())


def article(request, article_id):
    """获取文章详情"""
    article = get_object_or_404(Article, id=article_id)
    content_count = len(str(article.content))  # 统计文章字数

    # 获取上下篇
    per_article = Article.objects.filter(add_date__lt=article.add_date).last()
    next_article = Article.objects.filter(add_date__gt=article.add_date).first()
   
    # 判断是否为POST请求，如果不是
    if request.method != "POST":
        # 显示空表单
        form = CommentForm()
    else:
        # 否则显示空表单，并且获取表单输入的数据
        form = CommentForm(data=request.POST)
        # 验证数据的合法性
        if form.is_valid():
            # 将表单中的数据暂存到内存
            new_article = form.save(commit=False)
            new_article.author = request.user
            # 表单模型关联的文章为我们已经获取到的当前文章的id，在最开始处
            new_article.article = article
            # 保存
            new_article.save()
            # 成功之后跳转回当前页
            return HttpResponseRedirect(reverse('blog:article', args=[article_id]))
    return render(request, 'blog/article.html', locals())


def blog_get_dates(request, year, month):
    """ 文章归档列表页 """
    blog_dates = Article.objects.filter(add_date__year=year, add_date__month=month)
    return render(request, 'blog/dates.html', locals())


def blog_get_tags(request, tag_id):
    """ 标签列表页 """
    tag = get_object_or_404(Tags, id=tag_id)
    return render(request, 'blog/tags.html', locals())

blog/templates/blog/article.html
{% extends 'blog/base.html' %}
{% load static %}
{% block head %}
   <title>{{ article }}</title>
   <link rel="stylesheet" href="{% static 'blog/css/github.css' %}">
{% endblock head %}

{% block content %}

<div class="box is-shadowless is-radiusless">
  <div class=" is-pulled-right">
    <div class="tags has-addons">
        <span class="tag">本篇共</span>
        <span class="tag is-primary">{{ content_count }} 字</span><br>
       
    </div>
    
  </div>
    <h1 class=" is-size-5 has-text-weight-bold"><a href="">{{ article.title }}</a> </h1> 
    <p class="has-text-grey-light is-size-7" style="margin:1em 0;">
      <span>作者：<a href="">{{ article.author }}</a> </span>&nbsp;
      <span>分类：<a href="{% url 'blog:category' article.category.slug %}" target="_blank" rel="noopener noreferrer">{{ article.category }}</a> </span>&nbsp;
      <span>发布时间：{{ article.add_date|date }} </span>
    </p>
    <div class="content">
      <blockquote class=" is-size-7" style="margin-bottom:1em ">{{ article.desc }}</blockquote>
      <div class=" has-text-justified">
        {{ article.content|safe }}
      </div>
      <!-- <div class="has-text-right">
          <p class=" is-size-7 has-text-grey-light">
            本篇文章最后修改于：{{ article.pub_date|date }}
          </p>
      </div> -->
    </div> 

<!-- 文章标签 -->
    <div class="tags">
    {% if article.tags.all %}
      <span class="tag is-white has-text-black-ter is-paddingless">文章标签：</span>
      {% for tag in article.tags.all %}
        <span class="tag is-white is-paddingless">
          <a href="{% url 'blog:article' article.id %}">{{ tag }}</a>  
        </span>
      {% endfor %}
    {% else %}
        <p>无标签！</p>
    {% endif %}
    </div>
<!-- 文章标签 end-->
</div>

<!-- 上下篇 -->
<div class="box is-shadowless is-radiusless">
  <div class="columns">
    <div class="column is-6">
      {% if per_article %}
        <span class=" is-size-7">上一篇：</span>
        <a href="{% url 'blog:article' per_article.id %}">{{ per_article }}</a> 
        {% else %}
        <span class=" is-size-7">上一篇：</span>
        <span class=" has-text-danger">没有了！</span> 
      {% endif %}  
    </div>
    <div class="column is-6 has-text-right">
        {% if next_article %}
        <span class=" is-size-7">下一篇：</span>
        <a href="{% url 'blog:article' next_article.id %}">{{ next_article }}</a>  
        {% else %}
        <span class=" is-size-7">下一篇：</span>
        <span class=" has-text-danger">没有了！</span> 
      {% endif %}
    </div>
  </div>
</div>
  <!-- 上下篇 end-->


<!-- 留言内容 -->
<div class="box is-shadowless is-radiusless">
    <div class="tags has-addons is-pulled-right">
        <span class="tag">本篇共</span>
        <span class="tag is-primary">{{ article.comment_set.count }} 条评论</span><br>   
    </div>
  <h1 class="title is-size-5" id="comment">留言内容:</h1>
  {% if article.comment_set.all %}
    {% for comment in article.comment_set.all %}
  <article class="media" style="padding-left: 1em">
    <div class="media-content">
      <div class="content">
        <p>
          <span class="is-size-7 has-text-grey-light">
            <a href="">{{ comment.author }}</a> 于 {{ comment.add_date|date }}发表评论：</span><br>
           {{ comment.content }}
        </p>
        
      </div>
    </div>
  </article>
  {% endfor %} 
  {% else %}
    <p>还没有任何评论！</p>
  {% endif %}
</div>
<!-- 留言内容 end-->

<!-- 留言框 -->
<div class="box is-shadowless is-radiusless">
  {% if user.is_authenticated %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="button is-primary is-pulled-right" style="margin-top: 1em" type="submit" value="提交评论">
      <div class=" is-clearfix"></div>
    </form>
  {% else %}
    <p>你还没有登录，请 <a href="{% url 'login' %}">登录</a> 后再评论！还没有账号，请前往<a href="{% url 'account:register' %}"> 注册 </a>！</p>
  {% endif %}
</div>
<!-- 留言框 end -->
{% endblock content %}  

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load simple_tag %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href=" {% static 'blog/css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    {% block head %}
    <title>杨勇的博客首页</title>
    {% endblock head %}
</head>
<body>
<!-- 博客导航栏 -->
  <header class="container menu-header">
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <h1 class="navbar-item is-size-3 has-text-black">杨勇的博客</h1>
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          {% get_category_list as category_list %}
    {% if category_list %}
        <div class="navbar-start">
            <a class="navbar-item active has-text-black has-text-weight-bold" href="{% url 'blog:index' %}">
                首页
            </a>
        {% for category in category_list %}
            <a class="navbar-item has-text-black-bis" href="{% url 'blog:category' category.slug %}">
                {{ category.name }}
            </a>
        {% endfor %}    
           
        </div>
    {% else %}
        <p>还没有添加任何分类</p>
    {% endif %} 
    
        <div class="navbar-end">
          <div class="navbar-item">
            {% if user.is_authenticated %}
            <div class="buttons">
                <a href="{% url 'account:person' %}" class="button is-info">个人中心</a>
                <a href="{% url 'logout' %}" class="button is-primary">退出</a>
            </div>
            {% else %}
            <div class="buttons">
              <a href="{% url 'login' %}" class="button is-info">登录</a>
              <a href="{% url 'account:register' %}" class="button is-primary">注册</a>
            </div>
            {% endif %}
          </div>
          
        </div>

        </div>
    </nav>
  </header>

<!-- 博客导航栏  end-->


<!-- 博客section模块 -->
<div class="container">
  <section class="section has-background-light">
    <div class="columns">

      <!-- 博客左边内容模块 -->
      <div class="column is-8">
        {% block content %}
        {% endblock content %}      
      </div>
      <!-- 博客左边内容模块 -->

      <!-- 博客右侧列表模块 -->
      <div class="column is-4">  
          {% block aside %}

        <!-- 文章归档 -->
        {% get_month_list as archive_list %}
        <div class="box is-shadowless is-radiusless">
          <h1 class="title is-size-5">文章归档</h1>
          {% if archive_list %}
          {% for archive in archive_list %}
          <article class="media" >
              <div class="media-content" >
                <div class="content">
                
                <a href="{% url 'blog:dates' archive.year archive.month %}">{{ archive|date:"Y年m月" }}</a>  
                </div>
              </div>
            </article>
          {% endfor %}
      {% else %}
      <p>还没有任何评论！</p>
      {% endif %}
        </div>
        <!-- 文章归档 end -->

        
        <!-- 侧边栏评论 -->
        {% get_comment_list as comment_list %}
        <div class="box is-shadowless is-radiusless">
          <h1 class="title is-size-5" id="comment">最新评论</h1>
          {% if comment_list %}
              {% for comment in comment_list %}
              <article class="media" style="padding-left: 1rem;">
                  <div class="media-content" >
                    <div class="content">
                      <p>
                        <span class="is-size-7 has-text-grey-light">
                          <a href="">{{ comment.author }}</a> 于 {{ comment.add_date|date }}发表评论：</span><br>
                         <a href="{% url 'blog:article' comment.article.id %}">{{ comment.content }}</a>
                      </p>
                      
                    </div>
                  </div>
                </article>
              {% endfor %}
          {% else %}
          <p>还没有任何评论！</p>
          {% endif %}
        </div>
         <!-- 侧边栏评论 end-->

   <!-- 文章标签 -->
   {% get_tags_list as tags %}
   <div class="box is-shadowless is-radiusless">
     <h1 class="is-size-5 title">文章归档</h1>
     {% if tags %}
     {% for tag in tags %}
     <a href="{% url 'blog:tags' tag.id %}">
      <span class="tag">
        {{ tag }}
      </span>
    </a>
     {% endfor %}
    
 {% else %}
 <p>还没有任何评论！</p>
 {% endif %}
   </div>
   <!-- 文章标签 end -->

          {% endblock aside %} 
      </div>
      <!-- 博客右侧列表模块 end-->


    </div>
  </section>

  <!-- 博客底部通用 footer -->
  <footer>
  </footer>
   <!-- 博客底部通用 footer end-->
</div>
<!-- 博客content模块 end -->
</body>
</html>

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% block head %}
   <title>{{ category }}分类下的所有文章</title>
{% endblock head %}

{% block content %}
<!-- 显示当前分类模块 -->
<div class="box is-shadowless is-radiusless">
        当前分类：{{ category }}
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ category.article_set.count }} 篇</span>
        </div>
</div>
<!-- 显示当前分类模块 end-->


{% if category.article_set.all %}
{% for article in category.article_set.all %}
<div class="box is-shadowless is-radiusless">
    <h1 class=" is-size-5 has-text-weight-bold"><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a> </h1> 
    <p class="has-text-grey-light is-size-7" style="margin:1em 0;">
      <span>作者：<a href="">{{ article.author }}</a> </span>&nbsp;
      <span>分类：<a href="{% url 'blog:category' article.category.slug %}" target="_blank" rel="noopener noreferrer">{{ article.category }}</a> </span>&nbsp;
      <span>发布时间：{{ article.add_date }} </span>
    </p>
    <div class="content">
      {{ article.desc }}...

      <a href="{% url 'blog:article' article.id %}" class="button is-pulled-right is-primary" style="margin-top: 1em">阅读更多</a>
      <div class=" is-clearfix"></div>
    </div> 
</div>
{% endfor %}
{% else %}
    <p>还没有发布任何文章！</p>
{% endif %}
{% endblock content %}   

blog/templates/blog/dates.html
{% extends 'blog/base.html' %}
{% block head %}
   <title>{{ year }}年{{ month }}月文章归档</title>
{% endblock head %}

{% block content %}
<!-- 显示当前分类模块 -->
<div class="box is-shadowless is-radiusless">
        每月归档：{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ blog_dates.count }} 篇</span>
        </div>
</div>
<!-- 显示当前分类模块 end-->

{% if blog_dates %}
{% for article in blog_dates %}
<div class="box is-shadowless is-radiusless">
    <h1 class=" is-size-5 has-text-weight-bold"><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a> </h1> 
    <p class="has-text-grey-light is-size-7" style="margin:1em 0;">
      <span>作者：<a href="">{{ article.author }}</a> </span>&nbsp;
      <span>分类：<a href="{% url 'blog:category' article.category.slug %}" target="_blank" rel="noopener noreferrer">{{ article.category }}</a> </span>&nbsp;
      <span>发布时间：{{ article.add_date }} </span>
    </p>
    <div class="content">
      {{ article.desc }}...

      <a href="{% url 'blog:article' article.id %}" class="button is-pulled-right is-primary" style="margin-top: 1em">阅读更多</a>
      <div class=" is-clearfix"></div>
    </div> 
</div>
{% endfor %}
{% else %}
    <p>还没有发布任何文章！</p>
{% endif %}
{% endblock content %}   

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block head %}
  <title>杨勇的博客首页</title>
{% endblock head %}

{% block content %}
{% if article_list %}
{% for article in article_list %}
<div class="box is-shadowless is-radiusless">
    <h1 class=" is-size-5 has-text-weight-bold"><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a> </h1> 
    <p class="has-text-grey-light is-size-7" style="margin:1em 0;">
      <span>作者：<a href="">{{ article.author }}</a> </span>&nbsp;
      <span>分类：<a href="{% url 'blog:category' article.category.slug %}" target="_blank" rel="noopener noreferrer">{{ article.category }}</a> </span>&nbsp;
      <span>发布时间：{{ article.add_date }} </span>
    </p>
    <div class="content">
      {{ article.desc }}...

      <a href="{% url 'blog:article' article.id %}" class="button is-pulled-right is-primary" style="margin-top: 1em">阅读更多</a>
      <div class=" is-clearfix"></div>
    </div> 
</div>
{% endfor %}
{% else %}
  <p>还没有发布任何文章！</p>
{% endif %}
{% endblock content %}

blog/templates/blog/tags.html
{% extends 'blog/base.html' %}
{% block head %}
   <title>标签{{ tag }}下的文章</title>
{% endblock head %}

{% block content %}

<!-- 显示当前分类模块 -->
<div class="box is-shadowless is-radiusless">
    标签：{{ tag }}
    <div class="tags has-addons is-pulled-right">
      <span class="tag">共</span>
      <span class="tag is-primary">{{ tag.article_set.count }} 篇</span>
    </div>
</div>
<!-- 显示当前分类模块 end-->


{% if tag.article_set.all %}
{% for article in tag.article_set.all %}
<div class="box is-shadowless is-radiusless">
    <h1 class=" is-size-5 has-text-weight-bold"><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a> </h1> 
    <p class="has-text-grey-light is-size-7" style="margin:1em 0;">
      <span>作者：<a href="">{{ article.author }}</a> </span>&nbsp;
      <span>分类：<a href="{% url 'blog:category' article.category.slug %}" target="_blank" rel="noopener noreferrer">{{ article.category }}</a> </span>&nbsp;
      <span>发布时间：{{ article.add_date }} </span>
    </p>
    <div class="content">
      {{ article.desc }}...

      <a href="{% url 'blog:article' article.id %}" class="button is-pulled-right is-primary" style="margin-top: 1em">阅读更多</a>
      <div class=" is-clearfix"></div>
    </div> 
</div>
{% endfor %}
{% else %}
    <p>还没有发布任何文章！</p>
{% endif %}

{% endblock content %}